url: https://singhdivjeet.github.io/portfolio-website/

incremental: true

plugins:
  - jekyll-sitemap

# variables
name: Divjeet Singh's homepage
description: Divjeet Singh's homepage
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "TODO.txt", "Gemfile", "Gemfile.lock"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Collections
collections:
  bio:
    output: true
    name: Biography
    pos: 1
  honors:
    output: true
    name: Honors
    pos: 2
  publications:
    output: true
    name: Publications
    pos: 3
  projects:
    output: true
    name: Projects
    pos: 4
  cv:
    output: true
    name: CV
    pos: 5
  games:
    output: true
    name: Games
    pos: 6
  about:
    output: true
    name: About
    pos: 100

defaults:
  - scope:
      path: ""
    values:
      icon: "http://www.andrew.cmu.edu/user/zinanl/assets/img/file.ico"
